namespace CargaArchivoLiquidadores
{
    public partial class Liquidacion
    {
        public string Poliza { get; set; }
        public string TipoPoliza { get; set; }
        public string FormaPagoPoliza { get; set; }
        public string RutClienteContratante { get; set; }
        public string DigitoVerificadorContratante { get; set; }
        public string Contratante { get; set; }
        public string RutIntermediario { get; set; }
        public string DigitoVerificadorIntermediario { get; set; }
        public string ApellidoPaternoIntermediario { get; set; }
        public string ApellidoMaternoIntermediario { get; set; }
        public string NombreIntermediario { get; set; }
        public string TipoIntermediario { get; set; }
        public string Sucursal { get; set; }
        public string NombreSucursal { get; set; }
        public string RutAsegurado { get; set; }
        public string DvAsegurado { get; set; }
        public string ApellidoPaternoAsegurado { get; set; }
        public string ApellidoMaternoAsegurado { get; set; }
        public string NombreAsegurado { get; set; }
        public string RutPaciente { get; set; }
        public string DigitoVerificadorPaciente { get; set; }
        public string ApellidoPaternoPaciente { get; set; }
        public string ApellidoMaternoPaciente { get; set; }
        public string NombrePaciente { get; set; }
        public string Parentesco { get; set; }
        public string FechaNacimiento { get; set; }
        public string EdadPaciente { get; set; }
        public string SexoPaciente { get; set; }
        public string NumeroSolicitud { get; set; }
        public string CodigoDiagnostico { get; set; }
        public string DescripcionDiagnostico { get; set; }
        public string RutPrestador { get; set; }
        public string NombrePrestador { get; set; }
        public string TipoDocumento { get; set; }
        public string FolioDocumento { get; set; }
        public string AmbulatorioHospitalario { get; set; }
        public string PeriodoPrestacion { get; set; }
        public string FechaPrestacion { get; set; }
        public string FechaPresentacion { get; set; }
        public string PeriodoPresentacion { get; set; }
        public string SeqLiquidacion { get; set; }
        public string GrupoPrestacion { get; set; }
        public string DescripcionGrupoPrestacion { get; set; }
        public string CantidadPrestacion { get; set; }
        public decimal MontoPrestacion { get; set; }
        public decimal MontoPrestacionUf { get; set; }
        public decimal MontoIsapre { get; set; }
        public decimal MontoIsapreUf { get; set; }
        public decimal MontoSolicitado { get; set; }
        public decimal MontoSolicitadoUf { get; set; }
        public decimal MontoDeducible { get; set; }
        public decimal MontoDeducibleUf { get; set; }
        public decimal MontoPago { get; set; }
        public decimal MontoPagoUf { get; set; }
        public decimal MontoRechazo { get; set; }
        public decimal MontoRechazoUf { get; set; }
        public string Estado { get; set; }
        public string FechaEstado { get; set; }
        public string CorrSoliInterno { get; set; }
        public string NumeroRemesa { get; set; }
        public string FechaRemesa { get; set; }
        public string CodigoPrestacion { get; set; }
        public string DescripcionPrestacion { get; set; }
        public decimal PorcentajeReembolso { get; set; }
        public string CantidadPrestaciones { get; set; }
        public string FormaPagoLiquidacion { get; set; }
        public string CodigoBanco { get; set; }
        public string Banco { get; set; }
        public string CuentaCorriente { get; set; }
        public string RecepcionCheque { get; set; }
        public string FechaPago { get; set; }
        public string NumeroEgreso { get; set; }
        public string Observacion { get; set; }
        public string CodigoIsapre { get; set; }
        public string Isapre { get; set; }
        public string FechaContable { get; set; }
        public string CodigoPlan { get; set; }
        public string CodigoGrupo { get; set; }
        public string DescripcionGrupo { get; set; }
        public string PeriodoContable { get; set; }
        public string CorrBeneficiario { get; set; }
        public string TipoReembolso { get; set; }
        public string FechaInicioVigencia { get; set; }
        public string Proveedor { get; set; }
        public string Convenio { get; set; }
        public string Admin { get; set; }
        public string Observacion2 { get; set; }
        public string Liquidador { get; set; }
        public string CodigoMedicamento { get; set; }
        public string CodigoClasificacionBiometrica { get; set; }
        public string MontoTopeArancel { get; set; }
        public decimal MontoSaldoDisponible { get; set; }
        public string FechaExtraccion { get; set; }
        public string EstadoRemesa { get; set; }
        public string TipoDeducible { get; set; }
        public decimal TopeDeducible { get; set; }
        public string NombrePlan { get; set; }
        public string FechaCreacionRemesa { get; set; }
        public string UsuarioCreacionRemesa { get; set; }
        public string FechaRecepcionCompania { get; set; }
        public string Region { get; set; }
        public string SucursalRemesa { get; set; }
        public string FechaCierreRemesa { get; set; }
        public string ObservacionSolicitud { get; set; }
        public string PagoContratante { get; set; }
        public string FechaDigitacion { get; set; }
        public string FechaPagoProyectada { get; set; }
        public string DescripcionPago { get; set; }
        public string CantidadDocumentos { get; set; }
        public string GlosaMedicamentos { get; set; }
        public string PagoTerceros { get; set; }
        public string NumeroDenuncio { get; set; }
    }
}
